### ISSUE TITLE
Exception in thread "Thread-2" java.lang.NullPointerException: Cannot read the array length because "this.data" is null

### ISSUE THREAD

**Issue by YYHYlh** [kyo-w/router-router#5]
自己写的项目和开源的tomcat war项目都报这个问题，会导致项目无法运行

**Comment by YYHYlh** [comment]
Exception in thread "Thread-2" java.lang.NullPointerException: Cannot read the array length because "this.data" is null
        at kyodream.analysts.ObjectAnalysts$ObjectIter.hasNext(ObjectAnalysts.java:118)
        at com.kyodream.debugger.core.framework.SpringMvcHandler.analystsTargetObject(SpringMvcHandler.java:15)
        at com.kyodream.debugger.core.framework.FrameworkHandler.handler(FrameworkHandler.java:33)
        at com.kyodream.debugger.core.context.ContextBreakPointHandler.handlerServlet(ContextBreakPointHandler.java:86)
        at com.kyodream.debugger.core.context.TomcatHandler.setServletMap(TomcatHandler.java:98)
        at com.kyodream.debugger.core.context.TomcatHandler.recordMapper(TomcatHandler.java:81)
        at com.kyodream.debugger.core.context.TomcatHandler.analystsMapper(TomcatHandler.java:68)
        at com.kyodream.debugger.core.context.TomcatHandler.handlerTarget(TomcatHandler.java:44)
        at com.kyodream.debugger.core.context.ContextBreakPointHandler.handler(ContextBreakPointHandler.java:28)
        at com.kyodream.debugger.core.thread.DebuggerThread.run(DebuggerThread.java:53)
        at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by kyo-w** [comment]
抱歉，这个问题是在3.1旧版中存在的问题，在移植的过程中忘记同步这个问题了, springMvc新版和旧版的存储位置有所改变，现有的代码并没有提供判断，导致出现null获取。我会同步代码的，谢谢

**Comment by YYHYlh** [comment]
还有个小问题，我看源码的pom文件里写了--add-exports=jdk.jdi/com.sun.tools.jdi=ALL-UNNAMED，但提供的jar包好像没有生效，需要手动添加。
师傅的项目很棒，代码写得很好，我学到很多
